### ISSUE TITLE
duplicate component and children

### ISSUE THREAD

**Issue by The-Code-Monkey** [apjs/ReactVelocity#98]
can you make a duplicate button which makes a duplicate of the component and all of its children.

also can you make it so that it doesn't write <stateless /> or <stateful /> if you make a component that has nothing below it as it does nothing.

also maybe integrate react-router and react-router-redux in?

thanks Andy

p.s. if you want i can do a change and do a pr for you?

**Comment by menothe** [comment]
Hi, thanks for your message. We would like to encourage you to create the pr for any or all of these changes, and then we can make the merge accordingly.

regards,

**Comment by The-Code-Monkey** [comment]
Im gonna have a go at the duplication thing first and will make a separate pr for each issue when i come to it

**Comment by menothe** [comment]
Thank you

**Comment by The-Code-Monkey** [comment]
which branch do you want the base to be for the pr should i do testing -> master or master -> testing

**Comment by The-Code-Monkey** [comment]
i think i did the pr wrong ive never done one before sorry
